name: daytistics-landing
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./backend/src:/srv/app/src
      - ./backend/config:/srv/app/config
      - ./backend/database:/srv/app/database
      - ./backend/public:/srv/app/public
      - ./backend/node_modules:/srv/app/node_modules
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      HOST: "0.0.0.0"
      PORT: 1337
      APP_KEYS: "lXI2PYaRNpKUvoVVO37Jzg==,IEuswysbzhjOiXgaDWJUcw==,nQG94cq4sLkpy6KnTuGN6w==,4fEowdhOCtDZeYFulft5HQ=="
      API_TOKEN_SALT: "Aa21ijvbCb7AB9ZMnR/kvg=="
      ADMIN_JWT_SECRET: "kb+yZmuorf3RjBbf1ivrUQ=="
      TRANSFER_TOKEN_SALT: "YYz82YdLXLEnHelkvB1YMQ=="
    depends_on:
      - postgres

  nuxt:
    image: oven/bun:latest
    working_dir: /app
    command: ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "3000"]
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    environment:
      MEDIA_ADDRESS: http://localhost:1337
      API_ADDRESS: http://strapi:1337
      API_KEY: "ab0b8218bb5cdbf724a574a692e2a0da4e2eb370a88efb55fe565bc6e13ba3145a5369f3956d3aa52a0050ac2ed3903799270ad33e63c906cfaf4e06519dee63f034635c78bfb939ede6cb927a6a56e3c5157be2d15e13b82101c47f657adf4b0dbee3a1ecadd4abcbc06120d684211d345c7dabb12b0d9f40c2f89ab4b64521"
volumes:
  postgres_data:
